some more installation related (for static) problems fixed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1144,8 +1144,8 @@ fi
 # if apxs was still not found, then no DSO
 
 if test -z "$APXS"; then
-  echo "configure: warning: apxs was not found, DSO compilation will not be available." 1>&2
-  echo "configure: warning: You can use --with-apxs to specify where your apxs is." 1>&2
+  echo "configure: warning: **** apxs was not found, DSO compilation will not be available." 1>&2
+  echo "configure: warning: **** You can use --with-apxs to specify where your apxs is." 1>&2
   DSO="no_dso"
   ALL="static"
 else
@@ -1175,13 +1175,14 @@ echo "configure:1174: checking for --with-apache" >&5
 if test "${with_apache+set}" = set; then
   withval="$with_apache"
   
-  echo "$ac_t""$withval" 1>&6
+  AP_SRC=`cd $withval; pwd`
 
-    if test ! -f $withval/src/Makefile; then
-    echo "configure: warning: The sources in $withval have not been confgured, or wrong path specified." 1>&2
+    if test ! -f "$AP_SRC/src/include/httpd.h"; then
+    { echo "configure: error: $withval does not look like an Apache source directory." 1>&2; exit 1; }
   fi
-  AP_SRC=$withval
-  AP_INCLUDES="-I${withval}/src/include -I${withval}/src/os/unix"
+
+  echo "$ac_t""$AP_SRC" 1>&6
+  AP_INCLUDES="-I${AP_SRC}/src/include -I${AP_SRC}/src/os/unix"
 
   # note who owns the apache source directory
   AP_SRC_OWN="`ls -ld $AP_SRC | awk '{print $3}'`"
@@ -1194,8 +1195,8 @@ fi
 
 
 if test -z "$AP_SRC"; then
-  echo "configure: warning: No apache sources specified, static compilation will not be available." 1>&2
-  echo "configure: warning: You can use --with-apache to specify where your Apache sources are." 1>&2
+  echo "configure: warning: **** No apache sources specified, static compilation will not be available." 1>&2
+  echo "configure: warning: **** You can use --with-apache to specify where your Apache sources are." 1>&2
   STATIC="no_static"
 else
   STATIC="do_static"
@@ -1206,13 +1207,13 @@ if test "$STATIC" = "no_static" -a "$DSO" = "no_dso"; then
 fi
 
 echo $ac_n "checking for --with-python""... $ac_c" 1>&6
-echo "configure:1210: checking for --with-python" >&5
+echo "configure:1211: checking for --with-python" >&5
 # Check whether --with-python or --without-python was given.
 if test "${with_python+set}" = set; then
   withval="$with_python"
   
-  echo "$ac_t""$withval" 1>&6
-  PYTHON_SRC=$withval
+  PYTHON_SRC=`cd $withval; pwd`
+  echo "$ac_t""$PYTHON_SRC" 1>&6
 
 else
   echo "$ac_t""no" 1>&6
@@ -1224,7 +1225,7 @@ if test -z "$PYTHON_SRC"; then
   # Extract the first word of "python", so it can be a program name with args.
 set dummy python; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1228: checking for $ac_word" >&5
+echo "configure:1229: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PYTHON_BIN'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1263,7 +1264,7 @@ else
   # Extract the first word of "python", so it can be a program name with args.
 set dummy python; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1267: checking for $ac_word" >&5
+echo "configure:1268: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PYTHON_BIN'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1304,13 +1305,13 @@ fi
 
 # find out python version
 echo $ac_n "checking Python version""... $ac_c" 1>&6
-echo "configure:1308: checking Python version" >&5
+echo "configure:1309: checking Python version" >&5
 PyVERSION=`$PYTHON_BIN -c 'import sys; print sys.version[:3]'`
 echo "$ac_t""$PyVERSION" 1>&6
 
 # check if python is compiled with threads
 echo $ac_n "checking whether Python is compiled with thread support""... $ac_c" 1>&6
-echo "configure:1314: checking whether Python is compiled with thread support" >&5
+echo "configure:1315: checking whether Python is compiled with thread support" >&5
 PyTHREADS=`$PYTHON_BIN -c "import sys; print \"thread\" in sys.builtin_module_names"`
 if test "$PyTHREADS" = "1"; then
   echo "$ac_t""yes" 1>&6
@@ -1329,7 +1330,7 @@ fi
 
 # find out compiled in install prefix
 echo $ac_n "checking Python install prefix""... $ac_c" 1>&6
-echo "configure:1333: checking Python install prefix" >&5
+echo "configure:1334: checking Python install prefix" >&5
 PyEXEC_INSTALLDIR=`$PYTHON_BIN -c "import sys; print sys.exec_prefix"`
 echo "$ac_t""$PyEXEC_INSTALLDIR" 1>&6
 
@@ -1339,7 +1340,7 @@ PY_STD_LIB=${PyEXEC_INSTALLDIR}/lib/python${PyVERSION}
 
 # set python std library variable
 echo $ac_n "checking what libraries Python was linked with""... $ac_c" 1>&6
-echo "configure:1343: checking what libraries Python was linked with" >&5
+echo "configure:1344: checking what libraries Python was linked with" >&5
 
 if test -z "$PYTHON_SRC"; then
   PyLIBP=${PyEXEC_INSTALLDIR}/lib/python${PyVERSION}
@@ -1365,7 +1366,7 @@ LIBS="${LIBS} ${PY_LIBS}"
 echo "$ac_t""$PY_LIBS" 1>&6
 
 echo $ac_n "checking linker flags used to link Python""... $ac_c" 1>&6
-echo "configure:1369: checking linker flags used to link Python" >&5
+echo "configure:1370: checking linker flags used to link Python" >&5
 
 if test -z "$PYTHON_SRC"; then
   PyLFS=`grep "^LINKFORSHARED=" ${PyLIBPL}/Makefile | cut -f2 -d= | tr '\011\012\015' '   '`
@@ -1380,7 +1381,7 @@ LDFLAGS="${LDFLAGS} ${PY_LDFLAGS}"
 echo "$ac_t""$PY_LDFLAGS" 1>&6
 
 echo $ac_n "checking where Python include files are""... $ac_c" 1>&6
-echo "configure:1384: checking where Python include files are" >&5
+echo "configure:1385: checking where Python include files are" >&5
 
 if test -z "$PYTHON_SRC"; then
   PY_INCLUDES="-I${PyEXEC_INSTALLDIR}/include/python${PyVERSION}"
@@ -1392,8 +1393,7 @@ echo "$ac_t""$PY_INCLUDES" 1>&6
 
 
 
-echo $ac_n "checking for mkdep""... $ac_c" 1>&6
-echo "configure:1397: checking for mkdep" >&5
+# see if we have mkdep
 # Extract the first word of ""mkdep"", so it can be a program name with args.
 set dummy "mkdep"; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
@@ -1431,12 +1431,11 @@ fi
 
 
 if test -z "${MKDEP}"; then
-  echo $ac_n "checking for makedepend""... $ac_c" 1>&6
-echo "configure:1436: checking for makedepend" >&5
+  # or makedepend
   # Extract the first word of ""makedepend"", so it can be a program name with args.
 set dummy "makedepend"; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1440: checking for $ac_word" >&5
+echo "configure:1439: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_MKDEP'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1749,9 +1748,9 @@ test "$no_create" = yes || ${CONFIG_SHELL-/bin/sh} $CONFIG_STATUS || exit 1
 
 if test -n "$MKDEP"; then
   # make dependencies
-  echo "analyzing dependencies"
+  echo "analyzing dependencies" 
   cd src
-  make depend
+  make depend > /dev/null 2>&1
 fi
 
 
