added rudimentary tests, some documentation fixes, and more misc stuff

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1145,6 +1145,7 @@ fi
 
 
 
+
 if test -z "$APXS"; then
   echo "configure: warning: **** apxs was not found, DSO compilation will not be available." 1>&2
   echo "configure: warning: **** You can use --with-apxs to specify where your apxs is." 1>&2
@@ -1156,9 +1157,9 @@ else
 
   # check Apache version
   echo $ac_n "checking Apache version""... $ac_c" 1>&6
-echo "configure:1160: checking Apache version" >&5
-  httpd="`${APXS} -q SBINDIR`/`${APXS} -q TARGET`"
-  ver=`$httpd -v | awk '/version/ {print $3}' | awk -F/ '{print $2}'`
+echo "configure:1161: checking Apache version" >&5
+  HTTPD="`${APXS} -q SBINDIR`/`${APXS} -q TARGET`"
+  ver=`$HTTPD -v | awk '/version/ {print $3}' | awk -F/ '{print $2}'`
   echo "$ac_t""$ver" 1>&6
 
   # make version begins with 2
@@ -1168,19 +1169,19 @@ echo "configure:1160: checking Apache version" >&5
 
   # determine LIBEXEC
   echo $ac_n "checking for Apache libexec directory""... $ac_c" 1>&6
-echo "configure:1172: checking for Apache libexec directory" >&5
+echo "configure:1173: checking for Apache libexec directory" >&5
   LIBEXECDIR=`${APXS} -q LIBEXECDIR`
   echo "$ac_t""$LIBEXECDIR" 1>&6
 
   # determine INCLUDES
   echo $ac_n "checking for Apache include directory""... $ac_c" 1>&6
-echo "configure:1178: checking for Apache include directory" >&5
+echo "configure:1179: checking for Apache include directory" >&5
   AP_INCLUDES="-I`${APXS} -q INCLUDEDIR`"
   echo "$ac_t""$AP_INCLUDES" 1>&6
 
     if test "`uname`" = "SunOS"; then
     echo $ac_n "checking for gcc on Solaris possible missing _eprintf problem""... $ac_c" 1>&6
-echo "configure:1184: checking for gcc on Solaris possible missing _eprintf problem" >&5
+echo "configure:1185: checking for gcc on Solaris possible missing _eprintf problem" >&5
     if test "$CC" = "gcc"; then
       EPRINTF_HACK="_eprintf.o"
       FLOATDIDF_HACK="_floatdidf.o"
@@ -1194,6 +1195,7 @@ fi
 
 
 
+## static is disabled, thus no --with-apache
 ##AC_MSG_CHECKING(for --with-apache)
 # Check whether --with-apache or --without-apache was given.
 if test "${with_apache+set}" = set; then
@@ -1217,10 +1219,9 @@ if test "${with_apache+set}" = set; then
   AP_SRC_OWN="`ls -ld $AP_SRC | awk '{print $3}'`"
   AP_SRC_GRP="`ls -ld $AP_SRC | awk '{print $4}'`"
 
-else
-  echo "$ac_t""no" 1>&6
 fi
 
+##AC_MSG_RESULT(no))
 
 
 if test -z "$AP_SRC"; then
@@ -1236,7 +1237,7 @@ if test "$STATIC" = "no_static" -a "$DSO" = "no_dso"; then
 fi
 
 echo $ac_n "checking for --with-python""... $ac_c" 1>&6
-echo "configure:1240: checking for --with-python" >&5
+echo "configure:1241: checking for --with-python" >&5
 # Check whether --with-python or --without-python was given.
 if test "${with_python+set}" = set; then
   withval="$with_python"
@@ -1255,7 +1256,7 @@ if test -z "$PYTHON_SRC"; then
   # Extract the first word of "python", so it can be a program name with args.
 set dummy python; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1259: checking for $ac_word" >&5
+echo "configure:1260: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PYTHON_BIN'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1294,7 +1295,7 @@ else
   # Extract the first word of "python", so it can be a program name with args.
 set dummy python; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1298: checking for $ac_word" >&5
+echo "configure:1299: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PYTHON_BIN'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1335,13 +1336,13 @@ fi
 
 # find out python version
 echo $ac_n "checking Python version""... $ac_c" 1>&6
-echo "configure:1339: checking Python version" >&5
+echo "configure:1340: checking Python version" >&5
 PyVERSION=`$PYTHON_BIN -c 'import sys; print sys.version[:3]'`
 echo "$ac_t""$PyVERSION" 1>&6
 
 # find out compiled in install prefix
 echo $ac_n "checking Python install prefix""... $ac_c" 1>&6
-echo "configure:1345: checking Python install prefix" >&5
+echo "configure:1346: checking Python install prefix" >&5
 PyEXEC_INSTALLDIR=`$PYTHON_BIN -c "import sys; print sys.exec_prefix"`
 echo "$ac_t""$PyEXEC_INSTALLDIR" 1>&6
 
@@ -1351,7 +1352,7 @@ PY_STD_LIB=${PyEXEC_INSTALLDIR}/lib/python${PyVERSION}
 
 # set python std library variable
 echo $ac_n "checking what libraries Python was linked with""... $ac_c" 1>&6
-echo "configure:1355: checking what libraries Python was linked with" >&5
+echo "configure:1356: checking what libraries Python was linked with" >&5
 
 if test -z "$PYTHON_SRC"; then
   PyLIBP=${PyEXEC_INSTALLDIR}/lib/python${PyVERSION}
@@ -1382,7 +1383,7 @@ LIBS="${LIBS} ${PY_LIBS}"
 echo "$ac_t""$PY_LIBS" 1>&6
 
 echo $ac_n "checking linker flags used to link Python""... $ac_c" 1>&6
-echo "configure:1386: checking linker flags used to link Python" >&5
+echo "configure:1387: checking linker flags used to link Python" >&5
 
 if test -z "$PYTHON_SRC"; then
   PyLFS=`grep "^LINKFORSHARED=" ${PyLIBPL}/Makefile | cut -f2 -d= | tr '\011\012\015' '   '`
@@ -1397,7 +1398,7 @@ LDFLAGS="${LDFLAGS} ${PY_LDFLAGS}"
 echo "$ac_t""$PY_LDFLAGS" 1>&6
 
 echo $ac_n "checking where Python include files are""... $ac_c" 1>&6
-echo "configure:1401: checking where Python include files are" >&5
+echo "configure:1402: checking where Python include files are" >&5
 
 if test -z "$PYTHON_SRC"; then
   PY_INCLUDES="-I${PyEXEC_INSTALLDIR}/include/python${PyVERSION}"
@@ -1413,7 +1414,7 @@ echo "$ac_t""$PY_INCLUDES" 1>&6
 # Extract the first word of ""mkdep"", so it can be a program name with args.
 set dummy "mkdep"; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1417: checking for $ac_word" >&5
+echo "configure:1418: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_MKDEP'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1451,7 +1452,7 @@ if test -z "${MKDEP}"; then
   # Extract the first word of ""makedepend"", so it can be a program name with args.
 set dummy "makedepend"; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1455: checking for $ac_word" >&5
+echo "configure:1456: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_MKDEP'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1484,6 +1485,11 @@ else
 fi
 
 fi
+
+# this for the test.py script
+
+TEST_SERVER_ROOT="`pwd`/test"
+ln -fs ../../src/mod_python.so test/modules/mod_python.so
 
 trap '' 1 2 15
 cat > confcache <<\EOF
@@ -1598,7 +1604,7 @@ done
 ac_given_srcdir=$srcdir
 ac_given_INSTALL="$INSTALL"
 
-trap 'rm -fr `echo "Makefile src/Makefile src/libpython.module Doc/Makefile" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
+trap 'rm -fr `echo "Makefile src/Makefile src/libpython.module Doc/Makefile test/testconf.py" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
 EOF
 cat >> $CONFIG_STATUS <<EOF
 
@@ -1643,6 +1649,7 @@ s%@ALL@%$ALL%g
 s%@LIBEXECDIR@%$LIBEXECDIR%g
 s%@EPRINTF_HACK@%$EPRINTF_HACK%g
 s%@FLOATDIDF_HACK@%$FLOATDIDF_HACK%g
+s%@HTTPD@%$HTTPD%g
 s%@AP_SRC@%$AP_SRC%g
 s%@AP_SRC_OWN@%$AP_SRC_OWN%g
 s%@AP_SRC_GRP@%$AP_SRC_GRP%g
@@ -1652,6 +1659,7 @@ s%@PYTHON_BIN@%$PYTHON_BIN%g
 s%@PY_STD_LIB@%$PY_STD_LIB%g
 s%@INCLUDES@%$INCLUDES%g
 s%@MKDEP@%$MKDEP%g
+s%@TEST_SERVER_ROOT@%$TEST_SERVER_ROOT%g
 
 CEOF
 EOF
@@ -1693,7 +1701,7 @@ EOF
 
 cat >> $CONFIG_STATUS <<EOF
 
-CONFIG_FILES=\${CONFIG_FILES-"Makefile src/Makefile src/libpython.module Doc/Makefile"}
+CONFIG_FILES=\${CONFIG_FILES-"Makefile src/Makefile src/libpython.module Doc/Makefile test/testconf.py"}
 EOF
 cat >> $CONFIG_STATUS <<\EOF
 for ac_file in .. $CONFIG_FILES; do if test "x$ac_file" != x..; then
