disabled --with-apache

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1153,22 +1153,34 @@ if test -z "$APXS"; then
 else
   DSO="do_dso"
   ALL="dso"
-  
+
+  # check Apache version
+  echo $ac_n "checking Apache version""... $ac_c" 1>&6
+echo "configure:1160: checking Apache version" >&5
+  httpd="`${APXS} -q SBINDIR`/`${APXS} -q TARGET`"
+  ver=`$httpd -v | awk '/version/ {print $3}' | awk -F/ '{print $2}'`
+  echo "$ac_t""$ver" 1>&6
+
+  # make version begins with 2
+  if test -z "`echo $ver | egrep ^2`"; then
+    { echo "configure: error: This version of mod_python only works with Apache 2. The one you have seems to be $ver." 1>&2; exit 1; }
+  fi
+
   # determine LIBEXEC
   echo $ac_n "checking for Apache libexec directory""... $ac_c" 1>&6
-echo "configure:1160: checking for Apache libexec directory" >&5
+echo "configure:1172: checking for Apache libexec directory" >&5
   LIBEXECDIR=`${APXS} -q LIBEXECDIR`
   echo "$ac_t""$LIBEXECDIR" 1>&6
 
   # determine INCLUDES
   echo $ac_n "checking for Apache include directory""... $ac_c" 1>&6
-echo "configure:1166: checking for Apache include directory" >&5
+echo "configure:1178: checking for Apache include directory" >&5
   AP_INCLUDES="-I`${APXS} -q INCLUDEDIR`"
   echo "$ac_t""$AP_INCLUDES" 1>&6
 
     if test "`uname`" = "SunOS"; then
     echo $ac_n "checking for gcc on Solaris possible missing _eprintf problem""... $ac_c" 1>&6
-echo "configure:1172: checking for gcc on Solaris possible missing _eprintf problem" >&5
+echo "configure:1184: checking for gcc on Solaris possible missing _eprintf problem" >&5
     if test "$CC" = "gcc"; then
       EPRINTF_HACK="_eprintf.o"
       FLOATDIDF_HACK="_floatdidf.o"
@@ -1182,16 +1194,20 @@ fi
 
 
 
-echo $ac_n "checking for --with-apache""... $ac_c" 1>&6
-echo "configure:1187: checking for --with-apache" >&5
+##AC_MSG_CHECKING(for --with-apache)
 # Check whether --with-apache or --without-apache was given.
 if test "${with_apache+set}" = set; then
   withval="$with_apache"
   
+
+  # temporarily disable static on 2.0 until I figure out how to
+  # do it right
+  { echo "configure: error: Sorry, --with-apache (static compilation) is not supported at this time!" 1>&2; exit 1; }
+
   AP_SRC=`cd $withval; pwd`
 
-    if test ! -f "$AP_SRC/src/include/httpd.h"; then
-    { echo "configure: error: $withval does not look like an Apache source directory." 1>&2; exit 1; }
+    if test ! -f "$AP_SRC/include/httpd.h"; then
+    { echo "configure: error: $withval does not look like an Apache 2.0 source directory." 1>&2; exit 1; }
   fi
 
   echo "$ac_t""$AP_SRC" 1>&6
@@ -1208,8 +1224,8 @@ fi
 
 
 if test -z "$AP_SRC"; then
-  echo "configure: warning: **** No apache sources specified, static compilation will not be available." 1>&2
-  echo "configure: warning: **** You can use --with-apache to specify where your Apache sources are." 1>&2
+##  AC_MSG_WARN([**** No apache sources specified, static compilation will not be available.])
+##  AC_MSG_WARN([**** You can use --with-apache to specify where your Apache sources are.])
   STATIC="no_static"
 else
   STATIC="do_static"
@@ -1220,7 +1236,7 @@ if test "$STATIC" = "no_static" -a "$DSO" = "no_dso"; then
 fi
 
 echo $ac_n "checking for --with-python""... $ac_c" 1>&6
-echo "configure:1224: checking for --with-python" >&5
+echo "configure:1240: checking for --with-python" >&5
 # Check whether --with-python or --without-python was given.
 if test "${with_python+set}" = set; then
   withval="$with_python"
@@ -1239,7 +1255,7 @@ if test -z "$PYTHON_SRC"; then
   # Extract the first word of "python", so it can be a program name with args.
 set dummy python; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1243: checking for $ac_word" >&5
+echo "configure:1259: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PYTHON_BIN'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1278,7 +1294,7 @@ else
   # Extract the first word of "python", so it can be a program name with args.
 set dummy python; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1282: checking for $ac_word" >&5
+echo "configure:1298: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PYTHON_BIN'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1319,13 +1335,13 @@ fi
 
 # find out python version
 echo $ac_n "checking Python version""... $ac_c" 1>&6
-echo "configure:1323: checking Python version" >&5
+echo "configure:1339: checking Python version" >&5
 PyVERSION=`$PYTHON_BIN -c 'import sys; print sys.version[:3]'`
 echo "$ac_t""$PyVERSION" 1>&6
 
 # find out compiled in install prefix
 echo $ac_n "checking Python install prefix""... $ac_c" 1>&6
-echo "configure:1329: checking Python install prefix" >&5
+echo "configure:1345: checking Python install prefix" >&5
 PyEXEC_INSTALLDIR=`$PYTHON_BIN -c "import sys; print sys.exec_prefix"`
 echo "$ac_t""$PyEXEC_INSTALLDIR" 1>&6
 
@@ -1335,7 +1351,7 @@ PY_STD_LIB=${PyEXEC_INSTALLDIR}/lib/python${PyVERSION}
 
 # set python std library variable
 echo $ac_n "checking what libraries Python was linked with""... $ac_c" 1>&6
-echo "configure:1339: checking what libraries Python was linked with" >&5
+echo "configure:1355: checking what libraries Python was linked with" >&5
 
 if test -z "$PYTHON_SRC"; then
   PyLIBP=${PyEXEC_INSTALLDIR}/lib/python${PyVERSION}
@@ -1366,7 +1382,7 @@ LIBS="${LIBS} ${PY_LIBS}"
 echo "$ac_t""$PY_LIBS" 1>&6
 
 echo $ac_n "checking linker flags used to link Python""... $ac_c" 1>&6
-echo "configure:1370: checking linker flags used to link Python" >&5
+echo "configure:1386: checking linker flags used to link Python" >&5
 
 if test -z "$PYTHON_SRC"; then
   PyLFS=`grep "^LINKFORSHARED=" ${PyLIBPL}/Makefile | cut -f2 -d= | tr '\011\012\015' '   '`
@@ -1381,7 +1397,7 @@ LDFLAGS="${LDFLAGS} ${PY_LDFLAGS}"
 echo "$ac_t""$PY_LDFLAGS" 1>&6
 
 echo $ac_n "checking where Python include files are""... $ac_c" 1>&6
-echo "configure:1385: checking where Python include files are" >&5
+echo "configure:1401: checking where Python include files are" >&5
 
 if test -z "$PYTHON_SRC"; then
   PY_INCLUDES="-I${PyEXEC_INSTALLDIR}/include/python${PyVERSION}"
@@ -1397,7 +1413,7 @@ echo "$ac_t""$PY_INCLUDES" 1>&6
 # Extract the first word of ""mkdep"", so it can be a program name with args.
 set dummy "mkdep"; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1401: checking for $ac_word" >&5
+echo "configure:1417: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_MKDEP'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1435,7 +1451,7 @@ if test -z "${MKDEP}"; then
   # Extract the first word of ""makedepend"", so it can be a program name with args.
 set dummy "makedepend"; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1439: checking for $ac_word" >&5
+echo "configure:1455: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_MKDEP'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
