Added more detail to the warning message for ./configure when flex is not found or is not the correct version. Also added some information to the README detailing the flex requirements.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="src/mod_python.c"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT AR INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SET_MAKE APXS DSO ALL LIBEXECDIR SOLARIS_HACKS HTTPD AP_SRC AP_SRC_OWN AP_SRC_GRP STATIC PYTHON_BIN PY_STD_LIB INCLUDES TEST_SERVER_ROOT MOD_PYTHON_SO MP_VERSION PYTHON_SRC LEX MAX_LOCKS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT AR INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SET_MAKE APXS DSO ALL LIBEXECDIR SOLARIS_HACKS HTTPD AP_SRC AP_SRC_OWN AP_SRC_GRP STATIC PYTHON_BIN PY_STD_LIB INCLUDES TEST_SERVER_ROOT MOD_PYTHON_SO MP_VERSION PYTHON_SRC MAX_LOCKS LEX LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -803,8 +803,12 @@ Optional Packages:
 --with-apache=DIR 	Path to Apache sources
 --with-python=DIR	Path to specific Python binary
 --with-python-src=PATH	Path to python src - required to generate documenation
---with-flex=PATH	Path to specific flex binary
 --with-max-locks=INTEGER	Maximum number of locks
+--with-flex=PATH	Path to specific flex binary.
+	Flex Version 2.5.31 or greater is required to regenerate psp_parser.c
+	from psp_parse.l. A prepared psp_parser.c file is included with the
+	source, so you will only need flex if you make changes to psp_parser.l
+    	See the README for more information.
 
 Some influential environment variables:
   CC          C compiler command
@@ -3000,9 +3004,34 @@ fi;
 if test -z "$PYTHON_SRC"; then
   PYTHON_SRC=""
 fi
-# check for correct flex version
-# requires flex 2.5.31 for reentrant support
 
+# configure the MAX_LOCKS for number of mutex locks
+
+echo "$as_me:$LINENO: checking for --with-max-locks" >&5
+echo $ECHO_N "checking for --with-max-locks... $ECHO_C" >&6
+
+# Check whether --with-max-locks or --without-max-locks was given.
+if test "${with_max_locks+set}" = set; then
+  withval="$with_max_locks"
+
+  MAX_LOCKS="$withval"
+  echo "$as_me:$LINENO: result: $MAX_LOCKS" >&5
+echo "${ECHO_T}$MAX_LOCKS" >&6
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi;
+
+if test -z "$MAX_LOCKS"; then
+  MAX_LOCKS="8"
+fi
+echo "$as_me:$LINENO: result: Using $MAX_LOCKS MAX_LOCKS." >&5
+echo "${ECHO_T}Using $MAX_LOCKS MAX_LOCKS." >&6
+
+# Check for correct flex version
+# Requires flex 2.5.31 for reentrant support
+# See README for more details
 
 
 echo "$as_me:$LINENO: checking for --with-flex" >&5
@@ -3062,64 +3091,47 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-  if test -z "$LEX"; then
-    { { echo "$as_me:$LINENO: error: flex binary not found in path" >&5
-echo "$as_me: error: flex binary not found in path" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
 fi
 
 if test "$LEX" && test -x "$LEX"; then
   echo "$as_me:$LINENO: result: found $LEX, we'll use this. Use --with-flex to specify another." >&5
 echo "${ECHO_T}found $LEX, we'll use this. Use --with-flex to specify another." >&6
-else
-  { { echo "$as_me:$LINENO: error: flex $LEX not found,  Use --with-flex to specify another." >&5
-echo "$as_me: error: flex $LEX not found,  Use --with-flex to specify another." >&2;}
-   { (exit 1); exit 1; }; }
-fi
 
-echo "$as_me:$LINENO: checking flex version" >&5
+  echo "$as_me:$LINENO: checking flex version" >&5
 echo $ECHO_N "checking flex version... $ECHO_C" >&6
-FlexVERSION=`$LEX --version | sed 's/version//g' | awk '/flex/ {print $2}'`
-Flex_MAJOR_VER=`echo $FlexVERSION| awk -F .  '{print $1}'`
-Flex_MINOR_VER=`echo $FlexVERSION| awk -F .  '{print $2}'`
-Flex_SUB_VER=`echo $FlexVERSION| awk -F .  '{print $3}'`
-if test "$Flex_MAJOR_VER" -eq "2" && test "$Flex_MINOR_VER" -eq "5" && test "$Flex_SUB_VER" -ge "31"; then
-  echo "$as_me:$LINENO: result: $FlexVERSION. Good" >&5
+  FlexVERSION=`$LEX --version | sed 's/version//g' | awk '/flex/ {print $2}'`
+  Flex_MAJOR=`echo $FlexVERSION| awk -F .  '{print $1}'`
+  Flex_MINOR=`echo $FlexVERSION| awk -F .  '{print $2}'`
+  Flex_PATCH=`echo $FlexVERSION| awk -F .  '{print $3}'`
+
+  if test "$Flex_MAJOR" -eq "2" && test "$Flex_MINOR" -eq "5" && test "$Flex_PATCH" -ge "31"; then
+    echo "$as_me:$LINENO: result: $FlexVERSION. Good" >&5
 echo "${ECHO_T}$FlexVERSION. Good" >&6
-else
-  { echo "$as_me:$LINENO: WARNING: Flex version 2.5.31 or greater is required.  The one you have seems to be $FlexVERSION. Use --with-flex to specify another." >&5
-echo "$as_me: WARNING: Flex version 2.5.31 or greater is required.  The one you have seems to be $FlexVERSION. Use --with-flex to specify another." >&2;}
-fi
-
-
-# configure the MAX_LOCKS for number of mutex locks
-
-
-
-echo "$as_me:$LINENO: checking for --with-max-locks" >&5
-echo $ECHO_N "checking for --with-max-locks... $ECHO_C" >&6
-
-# Check whether --with-max-locks or --without-max-locks was given.
-if test "${with_max_locks+set}" = set; then
-  withval="$with_max_locks"
-
-  MAX_LOCKS="$withval"
-  echo "$as_me:$LINENO: result: $MAX_LOCKS" >&5
-echo "${ECHO_T}$MAX_LOCKS" >&6
+  else
+    { echo "$as_me:$LINENO: WARNING: Flex version $FlexVERSION found.
+    Version 2.5.31 or greater is required.  You can generally ignore this
+    warning unless you need to regenerate psp_parser.c from psp_parse.l.
+    If you do need regenerate psp_parser.c, use --with-flex to specify the
+    location of the correct flex version. See the README for more information." >&5
+echo "$as_me: WARNING: Flex version $FlexVERSION found.
+    Version 2.5.31 or greater is required.  You can generally ignore this
+    warning unless you need to regenerate psp_parser.c from psp_parse.l.
+    If you do need regenerate psp_parser.c, use --with-flex to specify the
+    location of the correct flex version. See the README for more information." >&2;}
+  fi
 
 else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi;
-
-
-if test -z "$MAX_LOCKS"; then
-  MAX_LOCKS="8"
+  { echo "$as_me:$LINENO: WARNING: flex $LEX not found
+  You can generally ignore this warning unless you need to regenerate
+  psp_parser.c from psp_parse.l.  If you do need regenerate psp_parser.c,
+  use --with-flex to specify the location of flex.
+  See the README for more information." >&5
+echo "$as_me: WARNING: flex $LEX not found
+  You can generally ignore this warning unless you need to regenerate
+  psp_parser.c from psp_parse.l.  If you do need regenerate psp_parser.c,
+  use --with-flex to specify the location of flex.
+  See the README for more information." >&2;}
 fi
-
-echo "$as_me:$LINENO: result: Using $MAX_LOCKS MAX_LOCKS." >&5
-echo "${ECHO_T}Using $MAX_LOCKS MAX_LOCKS." >&6
 
                                                                       ac_config_files="$ac_config_files Makefile src/Makefile Doc/Makefile src/include/mod_python.h test/testconf.py dist/setup.py dist/Makefile"
 cat >confcache <<\_ACEOF
@@ -3792,8 +3804,8 @@ s,@TEST_SERVER_ROOT@,$TEST_SERVER_ROOT,;t t
 s,@MOD_PYTHON_SO@,$MOD_PYTHON_SO,;t t
 s,@MP_VERSION@,$MP_VERSION,;t t
 s,@PYTHON_SRC@,$PYTHON_SRC,;t t
-s,@LEX@,$LEX,;t t
 s,@MAX_LOCKS@,$MAX_LOCKS,;t t
+s,@LEX@,$LEX,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
